const CONSTANTS = {
    APP_NAME: 'Chatster',
    SIGNUP: 'Sign Up',
    UPLOAD_FILE: 'Upload File',
    NAVIGATE_TO_REGISTER: 'Are you new? Click here for signing up',
    NAVIGATE_TO_LOGIN: 'Already have an account? Click here for log in',
    LOGIN: 'Login',
    SUCCESSFULLY_LOGGED_IN: 'Successfully Logged In',
    SUCCESSFULLY_SIGNED_UP: 'Successfully Signed Up',
    PASSWORD_NOT_SAME: 'Password Not Same',
    SIGNUP_FAILED: 'Signup Failed',
    SUCCESSFULLY_LOGGED_OUT: 'Successfully Logged Out',
    CLICK_HERE_TO_CHAT: 'Click here to chat',
    WELCOME: 'Welcome to',
    EMAIL_FIELD: 'email',
    PASSWORD_FIELD: 'password',
    EMAIL_LABEL: 'Email',
    PASSWORD_LABEL: 'Password',
    NAME_FIELD: 'name',
    NAME_LABEL: 'Name',
    CONFIRM_PASSWORD_FIELD: 'confirmPassword',
    CONFIRM_PASSWORD_LABEL: 'Confirm Password',
    VARIENT_OUTLINED: 'outlined',
    SUCCESS_COLOR: 'success',
    VARIENT_CONTAINED: 'contained',
    COMPONENT_LABEL: 'label',
    MARGIN_NORMAL: 'normal',
    TYPE_FILE: 'file',
    IMAGE_FIELD: 'imageURL',
    MARGIN_NONE: 'none',
    IMAGE_WIDTH_20: '20%',
    ENROUTE_LOGIN: '/',
    USERS_SCHEMA: 'users',
    USER_SCHEMA: 'user',
    USER_CHATS_SCHEMA: 'userChats',
    STYLED_DIV: 'div',
    COLUMN_DIRECTION: 'column',
    BGCOLOR_PRIMARY_MAIN: 'primary.main',
    ALIGN_CENTER: 'center',
    MARGIN_TOP_5: '5%',
    MAX_HEIGHT_70: '70vh',
    AUTO_COMPLETE_OFF: 'off',
    ENROUTE_REGISTER: '/register',
    ENROUTE_HOME: '/home',
    CHAT_WITH_USER_SCHEMA: 'chatWithUser',
    CURRENT_CHAT_SCHEMA: 'currentChat',
    ALT_PROFILE: 'Profile',
    LOADING: 'Loading',
    STYLED_SENDER: 'sender',
    STYLED_RECIEVER: 'reciever',
    CHATS_SCHEMA: 'chats',
    EMPTY_STRING: '',
    DISPLAY_NAME_ENTITY: 'displayName',
    EQUALS_SIGN: '==',
    ENTER_KEY: 'Enter',
    DOT_DATE: '.date',
    DOT_USER_INFO: '.userInfo',
    SEARCH_FOR_USER: 'Search For User',
    NAME_PLACEHOLDER: 'John Doe',
    TYPE_A_MESSAGE: 'Type a message',
    SEND_BUTTON: 'Send',
    APP_TITLE: 'Blog App',
    EMAIL: 'Email',
    PASSWORD: 'Password',
    ENTER_AN_EMAIL: 'Enter an Email Address',
    ENTER_PASSWORD: 'Enter your Password',
    LOGOUT: 'Logout',
    CREATE_AN_ACCOUNT: 'Create An Account',
    NAME: 'Name',
    CONFIRM_PASSWORD: 'Confirm Password',
    RE_ENTER_YOUR_PASSWORD: 'Re-enter Your Password',
    ENTER_YOUR_NAME: 'Enter Your Full Name',
    REGISTER: 'Register',
    ALREADY_EXISTS: 'Already have an account? Login',
    API_ERROR: 'API is not working properly',
    POSTS: 'Posts',
    COMMENTS: 'Comments',
    CREATE_NEW_POST: 'Create New Post',
    CLOSE_THE_DIALOG: 'Dismiss',
    NEW_POST: 'New Post',
    TITLE: 'Title',
    BODY: 'Body',
    PUBLISH_THE_POST: 'Publish',
    EDIT: 'Edit',
    DELETE: 'Delete',
    EDIT_DONE: 'Done',
    GO_BACK: 'Back to posts',
    POST: 'Post',
    PUBLISH_THE_COMMENT: 'Publish Comment',
    ADD_NEW_COMMENT: 'Add New Comment',
    POST_TITLE: 'Title: ',
    POST_BODY: 'Body: ',
    SOMETHING_WENT_WRONG: 'Something went wrong.',
    MY_PROFILE: 'My Profile',
    LOGIN_FIRST: 'Login first to check comments',
    DISLIKED: 'Disliked',
    DISLIKE: 'Dislike',
    LIKED: 'Liked',
    LIKE: 'Like',
    UNLIKE: 'Unlike',
    POSTED: 'Posted',
    EDITED: 'Edited',
    USER_ADDED: 'User Added',
    LOGGED_IN: 'Logged In',
    COMMENTED: 'Commented',
    UPDATED: 'Updated',
    PUBLISHED: 'published',
    NOT_PUBLISHED: 'not_published',
    SAVE: 'Save Post',
    PUBLISH_NOW: 'Publish Now',
    HIDE_PUBLISH: 'Hide this',
    PUBLISHED_SUCCESSFULLY: 'Published Succesfully',
    UNPUBLISHED_SUCCESSFULLY: 'Unpublished Successfully',
    UNPUBLISH_NOW: 'Unpublish Now',
    INCORRECT_EMAIL_OR_PASSWORD: 'Invalid Email or Password',
    USER_ALREADY_EXISTS: 'User already exists',
    ADD_ALL_FIELDS: 'Please add all fields',
    INVALID_USER_DATA: 'Invalid user data',
    ENTER_NAME: 'Please add a name',
    ENTER_EMAIL: 'Please enter email',
    NOT_AUTH_NO_TOKEN: 'Not authorized, no token',
    NOT_AUTHORIZED: 'Not Authorized',
    MINUS_PASSWORD: '-password',
    BEARER: 'Bearer',
    ENTER_TITLE: 'Please add title',
    ENTER_BODY: 'Please add body',
    ENTER_COMMENT: 'Please add comment',
    COMMENTS_SCHEMA: 'comments',
    POSTS_SCHEMA: 'posts',
    CANT_GET_INDIVIDUAL_POST: 'Cant get single post',
    EDIT_FAILED: 'Edit Failed',
    DELETION_FAILED: 'Deletion Failed',
    PUBLISH_NEW_POST_FAILED: 'Cant publish new post',
    PUBLISH_NEW_COMMENT_FAILED: 'Cant publish new comment',
    LOGIN_FAILED: 'Login failed',
    PROFILE_DATA_FAILED: 'Profile data loading failed',
    POST_FETCH_FAILED: 'Cant fetch all posts',
    COMMENTS_FETCH_FAILED: 'Cant fetch all comments',
    LIKE_DISLIKE_FAILED: 'Cant like or disliked',
    PUBLISHED_FAILED: 'Published Failied',
    UNPUBLISHED_FAILED: 'Unpublished Failed',
    GENERATE_TOKEN_FAILED: 'Generate Token Failed',
    LOGOUT_FAILED: 'Logout Failed',
    NEW_POST_FAILED: 'New Post Failed',
    DISLIKE_FAILED: 'Dislike Failed',
    LIKE_FAILED: 'Like Failed',
    FORM_TYPE_LOGIN: 'type-login',
    FORM_TYPE_SIGNUP: 'type-signup'
}

export default CONSTANTS